formats:
                      - json
                      - scss

path:

  root:
    src:                src/assets-dev
    dist:               src/assets

  tokens:
    src:                src/assets-dev/tokens/**/*.yml
    dist:
      json:             src/assets/tokens/json
      scss:             src/assets/scss/tokens

  clean:
                      - src/assets/**/*

  css:
    dist:               src/assets/css

  fonts:
    src:                src/assets-dev/fonts/**/*.{woff,woff2}
    dist:               src/assets/fonts

  icons:
    src:                src/assets-dev/icons/**/*.svg
    dist:               src/assets/icons

  scss:
    src:                src/assets-dev/scss/**/*.scss
    dist:               src/assets/scss
    watch:
                      - src/assets-dev/scss/**/*.scss
                      - src/assets/scss/partials/_icons-sprite.scss
                      - src/assets/scss/tokens/_tokens.scss

settings:

  icons:
    mode:
      symbol:
        sprite:         icons
      view:
        render:
          scss:
            dest:       ../../scss/partials/_icons-sprite.scss
        sprite:         icons
        prefix:         .icon-%s

  scss:
    browsers:
                      - last 2 versions
    devSuffix:          -dev
    fontPath:
      dev:              ../fonts
      prod:             ~usitc-ds/src/assets/fonts
    includePaths:
                      - node_modules
                      - src/assets/fonts
