formats:
                      - scss
                      - json
                      - es6
                      - node

path:

  root:
    src:                src/assets-dev
    dist:               src/assets

  tokens:
    src:                src/assets-dev/tokens/**/*.yml
    dist:
      tokens:           src/assets/tokens
      scss:             src/assets/scss/tokens

  clean:
                      - src/assets/css/**/*
                      - src/assets/fonts/**/*
                      - src/assets/icons/**/*
                      - src/assets/scss/**/*
                      - src/assets/tokens/**/*

  css:
    dist:               src/assets/css

  fonts:
    src:                src/assets-dev/fonts/**/*.{woff,woff2}
    dist:               src/assets/fonts

  icons:
    src:                src/assets-dev/icons/**/*.svg
    dist:               src/assets/icons

  scss:
    src:                src/assets-dev/scss/**/*.scss
    dist:               src/assets/scss
    watch:
                      - src/assets-dev/scss/**/*.scss
                      - src/assets/scss/partials/_icons-sprite.scss
                      - src/assets/scss/tokens/_tokens.scss

  styleguide:
    src:
                      - src/assets-dev/scss/**/*.scss
                      - src/assets-dev/tokens/**/*.yml

settings:

  tokens:
    json:
      fileName:         tokens.json
      jsonSpace:        '  '
    es6:
      fileName:         tokens.ts
      jsonSpace:        '  '
      exportModule:     export const tokens
    node:
      fileName:         tokens.js
      jsonSpace:        '  '
      exportModule:     true

  icons:
    mode:
      symbol:
        sprite:         icons
      view:
        render:
          scss:
            dest:       ../../scss/partials/_icons-sprite.scss
        sprite:         icons
        prefix:         .icon-%s

  scss:
    browsers:
                      - last 2 versions
    includePaths:
                      - node_modules
                      - src/assets/fonts

  styleguide:
    cmd:                /node_modules/kss-yaml/bin/kss --config src/styleguide/kss-config.json > src/assets/styleguide/kss.json
